# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftExample
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'RxSwiftExampleTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
    # Pods for testing
  end

  target 'RxSwiftExampleUITests' do
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
